"""initial schema

Revision ID: 786e98933b91
Revises: 
Create Date: 2026-02-20 14:40:33.158735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786e98933b91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('daily_summary_user_id_work_date_key'), 'daily_summary', type_='unique')
    op.create_unique_constraint('uq_daily_summary_user_date', 'daily_summary', ['user_id', 'work_date'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_daily_summary_user_date', 'daily_summary', type_='unique')
    op.create_unique_constraint(op.f('daily_summary_user_id_work_date_key'), 'daily_summary', ['user_id', 'work_date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
